"""Entity status sync: reads .meta.json files, compares with entity registry, updates on drift.

Backlog is deliberately absent. Backlog entities are DB-only
(``commands/add-to-backlog.md``): ``docs/backlog.md`` is a gitignored
projection regenerated by ``scripts/cleanup_backlog.py --apply``, and
"between re-projections the DB is authoritative; the file may lag."
Parsing that projection back into the registry made a lagging file
authoritative over the DB it was rendered from, so the backlog helper
was removed rather than repaired.
"""
import json
import os

# Feature/project valid statuses
STATUS_MAP = {"active", "completed", "abandoned", "planned", "promoted"}

# Brainstorm statuses that should not be re-archived
TERMINAL_STATUSES = {"promoted", "abandoned", "archived"}


def _sync_meta_json_entities(db, full_artifacts_path, subdir, entity_type, project_id, workspace_uuid=None):
    """Scan .meta.json files for a single entity type and sync status to entity registry.

    Args:
        db: EntityDatabase instance
        full_artifacts_path: absolute path to the artifacts root (e.g., /project/docs)
        subdir: subdirectory name to scan (e.g., "features", "projects")
        entity_type: entity type string (e.g., "feature", "project")
        project_id: project identifier

    Returns:
        {"updated": int, "skipped": int, "archived": int, "warnings": list[str]}
    """
    results = {"updated": 0, "skipped": 0, "archived": 0, "warnings": []}

    # FR-10: when workspace_uuid is supplied, suppress project_id to avoid
    # the shared workspace-identity resolution's DeprecationWarning (used
    # by update_entity's project_id->workspace_uuid alias, database.py,
    # feature 132 D6.4) on the post-FR-2 path.
    effective_project_id = project_id if workspace_uuid is None else None

    scan_dir = os.path.join(full_artifacts_path, subdir)
    if not os.path.isdir(scan_dir):
        return results

    for folder in os.listdir(scan_dir):
        meta_path = os.path.join(scan_dir, folder, ".meta.json")
        type_id = f"{entity_type}:{folder}"

        if not os.path.isfile(meta_path):
            # .meta.json deleted — archive entity if it exists
            try:
                db.update_entity(
                    type_id,
                    status="archived",
                    project_id=effective_project_id,
                    workspace_uuid=workspace_uuid,
                )
                results["archived"] += 1
            except ValueError:
                pass  # entity not in registry, skip
            continue

        try:
            with open(meta_path) as f:
                meta = json.load(f)
        except (json.JSONDecodeError, OSError) as e:
            results["warnings"].append(f"Failed to read {meta_path}: {e}")
            continue

        meta_status = meta.get("status")

        if meta_status not in STATUS_MAP:
            results["warnings"].append(f"Unknown status '{meta_status}' for {type_id}")
            continue

        entity = db.get_entity(type_id)  # returns None if not found
        if entity is None:
            results["skipped"] += 1  # entity not in registry
            continue

        if entity["status"] != meta_status:
            db.update_entity(
                type_id,
                status=meta_status,
                project_id=effective_project_id,
                workspace_uuid=workspace_uuid,
            )
            results["updated"] += 1
        else:
            results["skipped"] += 1

    return results


def sync_entity_statuses(db, full_artifacts_path, project_id="__unknown__",
                         artifacts_root="docs", project_root="",
                         workspace_uuid=""):
    """Scan all entity types and sync statuses to entity registry.

    Args:
        db: EntityDatabase instance
        full_artifacts_path: absolute path to the artifacts root (e.g., /project/docs)
        project_id: project identifier (legacy 12-char hex; pre-feature-108)
        artifacts_root: relative artifacts sub-path for stored artifact_path (e.g., "docs")
        project_root: absolute path to project root. If empty, derived from
                      full_artifacts_path by stripping artifacts_root suffix.
        workspace_uuid: optional workspace UUID (feature 108 / FR-12).
            Reserved for the post-Migration-11 reattribution path; today the
            value is recorded but DB writes still use ``project_id`` until
            the database.py method signatures are migrated.

    Returns:
        {"updated": int, "skipped": int, "archived": int,
         "registered": int, "deleted": int, "warnings": list[str]}

        ``deleted`` is retained in the shape (consumers assert its presence)
        and is structurally always 0: no helper deletes entities.
    """
    if not project_root:
        project_root = full_artifacts_path.removesuffix(artifacts_root).rstrip(os.sep)
        if not project_root:
            raise ValueError(
                f"Cannot derive project_root from full_artifacts_path={full_artifacts_path!r} "
                f"and artifacts_root={artifacts_root!r}"
            )

    results = {
        "updated": 0, "skipped": 0, "archived": 0,
        "registered": 0, "deleted": 0, "warnings": [],
    }

    ws_uuid_or_none = workspace_uuid or None
    helpers = [
        ("features", lambda: _sync_meta_json_entities(db, full_artifacts_path, "features", "feature", project_id, ws_uuid_or_none)),
        ("projects", lambda: _sync_meta_json_entities(db, full_artifacts_path, "projects", "project", project_id, ws_uuid_or_none)),
        ("brainstorms", lambda: _sync_brainstorm_entities(db, full_artifacts_path, artifacts_root, project_root, project_id, ws_uuid_or_none)),
    ]

    for name, helper in helpers:
        try:
            hr = helper()
        except Exception as exc:
            results["warnings"].append(f"{name}: {exc}")
            continue
        for key in ("updated", "skipped", "archived", "registered", "deleted"):
            results[key] += hr.get(key, 0)
        results["warnings"].extend(hr.get("warnings", []))

    return results


def _sync_brainstorm_entities(
    db, full_artifacts_path, artifacts_root, project_root, project_id, workspace_uuid=None
):
    """Scan brainstorms/ for .prd.md files; register new ones; archive missing ones.

    Part 1: Register unregistered .prd.md files as brainstorm entities.
    Part 2: Archive non-terminal brainstorm entities whose artifact file no longer exists (AC-9).

    Returns:
        {"registered": int, "archived": int, "skipped": int}
    """
    results = {"registered": 0, "archived": 0, "skipped": 0}
    brainstorms_dir = os.path.join(full_artifacts_path, "brainstorms")

    if not os.path.isdir(brainstorms_dir):
        return results

    # FR-10: suppress project_id when workspace_uuid is supplied (see _sync_meta_json_entities).
    effective_project_id = project_id if workspace_uuid is None else None

    # Part 1: scan filesystem for .prd.md files, register new entities
    seen_on_disk = set()  # entity_ids with files present on disk
    for filename in os.listdir(brainstorms_dir):
        if filename == ".gitkeep" or not filename.endswith(".prd.md"):
            continue

        stem = filename[: -len(".prd.md")]
        seen_on_disk.add(stem)
        type_id = f"brainstorm:{stem}"

        existing = db.get_entity(type_id)
        if existing is not None:
            results["skipped"] += 1
            continue

        artifact_path = os.path.join(artifacts_root, "brainstorms", filename)
        # F12 audit: idempotent reconciliation → upsert_entity
        db.upsert_entity(
            entity_type="brainstorm",
            entity_id=stem,
            name=stem,
            artifact_path=artifact_path,
            status="active",
            workspace_uuid=workspace_uuid,
            project_id=effective_project_id,
        )
        results["registered"] += 1

    # Part 2: archive non-terminal brainstorm entities whose file is missing (AC-9)
    # Workspace-scoped: an unscoped read returns every workspace's brainstorms
    # (database.py list_entities — absent filter means all workspaces), and the
    # archival write below would then reach entities this invocation does not own.
    entities = db.list_entities(
        entity_type="brainstorm",
        project_id=effective_project_id,
        workspace_uuid=workspace_uuid,
    )
    for entity in entities:
        if entity["entity_id"] in seen_on_disk:
            continue
        if entity.get("status", "") in TERMINAL_STATUSES:
            continue
        if not entity.get("artifact_path"):
            continue
        try:
            db.update_entity(
                entity["type_id"],
                status="archived",
                project_id=effective_project_id,
                workspace_uuid=workspace_uuid,
            )
            results["archived"] += 1
        except ValueError:
            pass  # entity disappeared between list and update, skip

    return results
