"""Brainstorm registration: the checkout's new ``.prd.md`` files join the registry.

Session start runs this as the reconciliation orchestrator's Task 1. It is
the only path by which brainstorms reach the registry: ``/pd:brainstorm``
registers nothing.

Nothing here reads the checkout's files back into what the registry already
holds (design W1: pd's own writers write the registry):

- **Features and projects:** their ``.meta.json`` files are projections of
  the registry, so no status and no archive flag is taken from them, or from
  their absence.
- **Brainstorms:** a registered brainstorm whose ``.prd.md`` this checkout
  lacks is left alone, since a branch or worktree can lack a file the
  registry rightly holds. ``/pd:cleanup-brainstorms`` archives explicitly,
  through ``update_entity(archived=true)``.
- **Backlog:** deliberately absent. Backlog entities are DB-only
  (``commands/add-to-backlog.md``): ``docs/backlog.md`` is a gitignored
  projection regenerated by ``scripts/cleanup_backlog.py --apply``, and
  "between re-projections the DB is authoritative; the file may lag."
  Parsing that projection back into the registry made a lagging file
  authoritative over the DB it was rendered from, so the backlog helper
  was removed rather than repaired.
"""
import os


def sync_entity_statuses(db, full_artifacts_path, project_id="__unknown__",
                         artifacts_root="docs", project_root="",
                         workspace_uuid=""):
    """Register the checkout's new brainstorms (the orchestrator's Task 1).

    Args:
        db: EntityDatabase instance
        full_artifacts_path: absolute path to the artifacts root (e.g., /project/docs)
        project_id: project identifier (legacy 12-char hex; pre-feature-108)
        artifacts_root: relative artifacts sub-path for stored artifact_path (e.g., "docs")
        project_root: absolute path to project root. If empty, derived from
                      full_artifacts_path by stripping artifacts_root suffix.
        workspace_uuid: optional workspace UUID (feature 108 / FR-12).
            Brainstorm registration always takes a workspace uuid: this
            one, else the workspace ``project_id`` names (C5b).

    Returns:
        {"registered": int, "skipped": int, "warnings": list[str]}: the
        brainstorm helper's counts. A helper failure is returned as a
        warning, never raised, so session start carries on.
    """
    if not project_root:
        project_root = full_artifacts_path.removesuffix(artifacts_root).rstrip(os.sep)
        if not project_root:
            raise ValueError(
                f"Cannot derive project_root from full_artifacts_path={full_artifacts_path!r} "
                f"and artifacts_root={artifacts_root!r}"
            )

    results = {"registered": 0, "skipped": 0, "warnings": []}
    try:
        brainstorms = _sync_brainstorm_entities(
            db, full_artifacts_path, artifacts_root, project_root, project_id,
            workspace_uuid or None,
        )
    except Exception as exc:
        results["warnings"].append(f"brainstorms: {exc}")
        return results
    results["registered"] = brainstorms["registered"]
    results["skipped"] = brainstorms["skipped"]
    return results


def _sync_brainstorm_entities(
    db, full_artifacts_path, artifacts_root, project_root, project_id, workspace_uuid=None
):
    """Register the ``.prd.md`` files in ``brainstorms/`` that the registry lacks.

    Registration only. A registered brainstorm whose file is missing stays as
    it is (W1.1): ``/pd:cleanup-brainstorms`` archives explicitly.

    Returns:
        {"registered": int, "skipped": int}
    """
    results = {"registered": 0, "skipped": 0}
    brainstorms_dir = os.path.join(full_artifacts_path, "brainstorms")

    if not os.path.isdir(brainstorms_dir):
        return results

    # FR-10: with a workspace_uuid given, the legacy project_id is not
    # passed on, which avoids the shared workspace-identity resolution's
    # DeprecationWarning (feature 132 D6.4) on the post-FR-2 path.
    effective_project_id = project_id if workspace_uuid is None else None
    # Registration takes one workspace (C5b): the given one, else the one the
    # legacy project_id names, resolved under register_entity's name, so an
    # unknown project_id reports the message register_entity's former
    # project_id parameter gave. Resolved at the first registration, so a
    # sync that registers nothing resolves no workspace.
    registration_workspace_uuid = None

    for filename in os.listdir(brainstorms_dir):
        if filename == ".gitkeep" or not filename.endswith(".prd.md"):
            continue

        stem = filename[: -len(".prd.md")]
        type_id = f"brainstorm:{stem}"

        existing = db.get_entity(type_id)
        if existing is not None:
            results["skipped"] += 1
            continue

        artifact_path = os.path.join(artifacts_root, "brainstorms", filename)
        if registration_workspace_uuid is None:
            registration_workspace_uuid = db._resolve_optional_workspace_filter(
                workspace_uuid, effective_project_id, _caller="register_entity"
            )
        # F12 audit: idempotent reconciliation → upsert_entity
        db.upsert_entity(
            entity_type="brainstorm",
            display_id=stem,
            name=stem,
            artifact_path=artifact_path,
            status="active",
            workspace_uuid=registration_workspace_uuid,
        )
        results["registered"] += 1

    return results
